### ISSUE TITLE
[BUG] Pokemon Colosseum Custom Starter glitch

### ISSUE THREAD

**Issue by JohnC911** [rotobash/pokemon-ngc-rando#10]
The Custom Starter for Starter 2 not working and instead using Starter 1 in Pokemon Colosseum. 

I clicked to use Custom on the Starters. I then select the Starter 1 and Starter 2 but when I ran the game it has used only the pokemon for Starter 1 for both Starters. For example I selected Pikacu for Starter 1 and then for Starter 2 I select Squirtle. When I ran the game instead of getting Squirtle as the second Starter I get 2 Pikacu's. I try both US version and European to test. 

This was run in Windows

By the way when I select Random or one of the Random Stages in the Starter it works to randomize both Starters. 

![Pokemon Colosseum settings](https://user-images.githubusercontent.com/83100301/139605882-832aca8d-4542-4fc2-b968-46c96af1ab9d.PNG)

**Comment by rotobash** [comment]
Hey there, thanks for reporting this!

I've made a new release with this fix. I think the auto updater in the current version is bonked, so please update from GitHub (it should be fixed now)

Cheers
