### ISSUE TITLE
[BUG] Randomizing Trainers Doesn't Work for XD

### ISSUE THREAD

**Issue by XModxGodX** [rotobash/pokemon-ngc-rando#16]
The randomizer doesn't work for trainers in XD I tested and it does seem to work for Colosseum.

I also tried randomizing it with just the trainer randomizer but I included the settings file anyways
[settings.zip](https://github.com/rotobash/pokemon-ngc-rando/files/7490699/settings.zip)
.

**Comment by rotobash** [comment]
Hey there, thanks for reporting this! 

I'm a bit busy with work this week but I'll take a look asap and try to have a fix by this weekend. You can probably use the older version (1.0.6-beta) in the meantime.

Cheers

**Comment by rotobash** [comment]
Had some time this morning to take a look and it turned out to be easier than I expected 😅
It should be good to go now. Let me know if you notice anything else

Cheers
