### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DeadByte9** [rotobash/pokemon-ngc-rando#23]
Rando evos are still not working im evolving mareep into flaaffy 

![image](https://user-images.githubusercontent.com/91769628/150882723-dc27c2a2-12b6-407f-815d-9c036b057f53.png)

![image](https://user-images.githubusercontent.com/91769628/150882865-76d7ff67-f79a-46a5-8642-a211c7f67637.png)

**Comment by rotobash** [comment]
Hey sorry you encountered this bug again, I suppose I didn't fix it the first time 😅

Anyway, I found the issue and it should be fixed for real this time. I've made a new release so please check it out when you can. Thanks for raising an issue!
