### ISSUE TITLE
[SUGGESTION]MasterBalls in marts

### ISSUE THREAD

**Issue by Nagitox** [rotobash/pokemon-ngc-rando#27]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but in my randomizer, I ran into MasterBall, that cost 0 ₽, and it is tempting to buy, even though the game might be easier.

**Describe the solution you'd like**
Maybe, if it's possible to code, when checking the "Random marts item" option, an option to ban MasterBalls, or fix another price to those Item could be propose ?

**Additional context**
![Capture d’écran (113)](https://user-images.githubusercontent.com/97539611/157129410-71fb51f7-4692-4dde-b5e5-487267660565.png)

I know there are other Item costing 0 ₽, so maybe the same solution could be applied to those items ?

**Comment by rotobash** [comment]
I set the masterball price to 30 000

I know you suggested 100 000 in our Discord chat but I felt that may have been prohibitively expensive and having the master ball in the mart would be a waste of a item slot. So I took the most expensive item in the game and tripled the price. Hopefully this is a good middle ground.
