### ISSUE TITLE
[SUGGESTION] Random legal moves only?

### ISSUE THREAD

**Issue by grehgg** [rotobash/pokemon-ngc-rando#29]
Would it be possible make a setting to randomize moves but limit to legal moves only? There is a randomizer for the GBA games that does this (https://www.reddit.com/r/PokemonROMhacks/comments/159cta/pokemon_3rd_gen_reasonable_randomizer/), I don't know if that helps, but that's exactly what I'm looking for. Thanks.

**Comment by rotobash** [comment]
Hi, sorry for the wait. I think I've implemented what you're asking for.

It takes the list of level up moves, TM moves and Tutor moves and uses that as the list to pick from. Other filters like prefer type and banning dragon rage should apply as well. Let me know if something isn't working as intended and I'll look into it. Cheers!
