### ISSUE TITLE
Guarantee Shadow Lugia is randomized into a Legendary

### ISSUE THREAD

**Issue by TheWrathAbove** [rotobash/pokemon-ngc-rando#36]
As amusing as it was to have the ultimate shadow pokemon be a Cascoon; it was pretty anti-climatic. Having an option to guarantee that the Shadow Lugia is randomized into a Legendary would go a long way to making the final boss feel more climactic.

**Comment by rotobash** [comment]
Hi again, thanks for the suggestion.

This should be easy enough to implement. I'll take a crack at it this weekend.

**Comment by rotobash** [comment]
Think I have this sorted out now. I made it Legendary -> Legendary so the same thing would happen for the dogs in Colosseum.

**Comment by TheWrathAbove** [comment]
Ah that's a good option. Greevil's legendary birds should probably also be in that group tho.

**Comment by rotobash** [comment]
Yep, anything legendary gets turned into a legendary. I also found out my legendary list isn't correct either, this actually fixes the "No Legendaries" option as well.

Thanks again for opening an issue!
