### ISSUE TITLE
2/3 Random Number Generator options fail.[BUG]

### ISSUE THREAD

**Issue by KCorruption** [rotobash/pokemon-ngc-rando#37]
(Made an edit, to make it easier to see the screenshot.)
**Describe the bug**
Only one of the three available random number generator options allows for the successful creation of a randomized ISO file.
I describe this & my process in a little more detail below.

**Settings used**
[https://cdn.discordapp.com/attachments/947956879978528808/977710224574136380/Colosseum.settings](url)

**Screenshots**
![image](https://user-images.githubusercontent.com/63965160/169672128-847753da-ad3d-4579-bf1c-23bd3893450d.png)

Windows 10 Home Edition (64bit)
Version 21H2
16gb RAM
Processor: AMD Ryzen 5 1600
GPU: Radeon RX 480 (4GB)

Version of App being used: 1.2.0.0
Settings Attempted: (Pokémon Colosseum)
Random Number Generator: (Xoroshiro128), Result: Fail-state with "Done!" output.
Application fails at "Randomizing Pokemon Traits".
Attempted saving new ISO in both the original ISO's folder location/drive, as well as in a different location/drive. Same result.
Attempted with the program launched as user, and again as admin.

Random Number Generator: (Net), Result: Fail-state with "Done!" output.
Application fails at "Randomizing Pokemon Traits".
Attempted saving new ISO in both the original ISO's folder location/drive, as well as in a different location/drive. Same result.
Attempted with the program launched as user, and again as admin.

Random Number Generator: (Cryptographic), Result: Finished/Completed, with "Done!" output.
No errors detected, as both user, and as admin. Newly generated ISO runs without error, in Dolphin.

Settings toggled/Modified Per App Tab:
[Trainers & Wilds]
Randomize Pokemon, No Duplicate Shadows

[Pokemon Traits]
(Base Stats: Randomize)

(Abilities: Randomize, Allow Wonder Guard, Ban Bad Abilities)

(Types: Randomize, Follow Evolution)

(Evolutions: Randomize, Fix Impossible)

[Starters, Trades and Gifts]
(Starters: Random)

(Trades: Randomize Given)

[TMs & Tutors]
(TMs: Randomize TMs)

(Compatibility: Full Compatibility)

[Moves & Movesets]
(Movesets: Completely Random, Every Pokemon Starts with 4 Moves, Ban Shadow Moves)

[Items]
(Misc: Ban Bad Items)

**Comment by rotobash** [comment]
Hi there, thanks for raising this issue.

Looks like this was two separate bugs. The first was the .Net RNG never worked if the seed wasn't specified (which is the default lol), The second was because of the "Randomize BST" option that would cause an out of bounds error when trying to update the values (only on Xoroshiro). The cryptographic RNG bypassed both of these bugs due to how it was implemented.

Think this should be okay now. I have a few other fixes to add before I make another release but it should be soon. Hopefully this will fix the issue for DracoSafarius as well.

**Comment by rotobash** [comment]
Just wanted to let you know the new release is out! Check it out if you have the chance to 👍
