### ISSUE TITLE
Randomize into Pokemon with a similar BST [SUGGESTION]  

### ISSUE THREAD

**Issue by TheWrathAbove** [rotobash/pokemon-ngc-rando#43]
I would like an option that looks at a given pokemon it's randomizing and only chooses a pokemon with a similar BST to randomize it to. I personally like this feature in other pokemon randomizers, because it creates a more linear difficulty curve and prevents stuff like endgame trainers using Butterfree, or early game trainers using Metagross.

EX: Charizard has BST of 534 and can be randomized to Milotic with a BST of 540 because it's stat total is within 20 points (or a possibly customizable number of points) of Charizard. On the other hand Spinarak at a BST of 250 wouldn't be allowed to randomize to Vigoroth with a BST of 440 because there's to large a discrepency.

**Comment by rotobash** [comment]
Hey, thanks for the suggestion.

This should be easy to implement, there's already a check for battle bingo to use "strong" pokemon which is essentially the same thing. How it works for battle bingo is that it looks first for a pokemon that has the exact same BST, if it can't find one it gradually widens the search till it finds one that matches. So they should always be somewhat close if I were to use the same logic.

**Comment by rotobash** [comment]
Just wanted to let you know the new release is out! Check it out if you have the chance to 👍
