### ISSUE TITLE
[BUG] randomizer stuck at randomizing Pokemon traits 

### ISSUE THREAD

**Issue by DeadByte9** [rotobash/pokemon-ngc-rando#51]
![20220529_235528.jpg](https://user-images.githubusercontent.com/91769628/170914498-bb9237e0-5f5e-47b2-8761-85cff188237a.jpg) it never done this before it would go straight to unpacking ISO but it seems to be linked to the evolutions with similar strength cause I tried unchecking everything else and they all worked

**Comment by DeadByte9** [comment]
It also happened when I did force fully evolved

**Comment by rotobash** [comment]
Hi there, thanks for reporting this.

Looks like those were two separate issues, the first being that "use similar strength" would sometimes have no pokemon to ick from initially so it looped forever trying to find one of similar strength. The second was that sometimes Pokemon could evolve into themselves, so the force fully evolved would get caught in a loop trying to pick the latest evolution.

I'll make a new release now
