### ISSUE TITLE
[BUG] new update has a new update?

### ISSUE THREAD

**Issue by DeadByte9** [rotobash/pokemon-ngc-rando#53]
everytime i try to open the updated randomizer it says it has a new update and it deletes everything from the files and it won't open anymore

**Comment by rotobash** [comment]
Oops my bad, guess I shouldn't be making releases in the middle of the night 😂 

I uploaded the correct versions to the release, if you update again it should stop asking you. Thanks for letting me know.

**Comment by rotobash** [comment]
Reading your comment again, I might have to take a look at the autoupdater some more. Does it normally work as intended for you?

**Comment by DeadByte9** [comment]
No it says error with app.config is missing

**Comment by DeadByte9** [comment]
@rotobash

**Comment by rotobash** [comment]
I was testing the autoupdater a bit and while it downloads the zip, it just wipes the folder and crashes. Not very ideal. 

I'm going to work on it a bit more, fix those issues, and make it not delete the app.config when updating. I made an issue to keep track of the progress on that. You can follow it here #56 

Thanks again for the report.

**Comment by Icarushollow** [comment]
autoupdater still deletes everything when ran, late 2023
