### ISSUE TITLE
[BUG] Object reference not set to an instance of an object when trying to randomize

### ISSUE THREAD

**Issue by Gabbyxo97** [rotobash/pokemon-ngc-rando#54]
**Describe the bug**
When I try to randomize (Pokemon Colosseum, Europe version), I get an error: Object reference not set to an instance of an object

Full error at additional context

**Settings You Used**
[main.settings.txt](https://github.com/rotobash/pokemon-ngc-rando/files/8814872/main.settings.txt)
(it's saved as .settings which isn't allowed hence the rename)

**Expected behavior**
I expect the game to be randomized

**Screenshots**
![Screenshot 2022-06-01 160905](https://user-images.githubusercontent.com/66498212/171424681-13c86289-d1c0-4ecd-97f0-f945ba61f018.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.EndInvoke(IAsyncResult asyncResult)
   at Randomizer.MainForm.StartRandomizing(Object sender, DoWorkEventArgs e) in C:\Users\mike\Documents\personal code\Pokemon-NGC-Rando\Pokemon-XD-Tool\MainForm.cs:line 254
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by rotobash** [comment]
Hi, thanks for reporting this.

I actually remember encountering this error too but totally forgot to fix it, whoops 😅 
Should be fixed now and I've made a new release.
