### ISSUE TITLE
[BUG] Randomizing item held item ???

### ISSUE THREAD

**Issue by Gabbyxo97** [rotobash/pokemon-ngc-rando#57]
**Describe the bug**
When randomizing held items, my first snagged Pokemon had the ??? item, which does nothing and is unable to be deposited in the bag (it'll give the error bag is full)

(I don't know if the same bug would occur with chest items)

**Settings You Used**
[simple.settings.txt](https://github.com/rotobash/pokemon-ngc-rando/files/8836305/simple.settings.txt)

**Expected behavior**
I expect the game only to give actual items, not ??? bug/placeholder items

**Screenshots**
![scr1_triplequestionmarkitem](https://user-images.githubusercontent.com/66498212/171969559-6293b6f1-68de-41a6-9089-1893fefba00f.png)
![scr2_triplequestionmarkitem](https://user-images.githubusercontent.com/66498212/171969563-6fb67bd8-2e15-478b-944f-d7821b3d0446.png)

**Desktop (please complete the following information):**
Windows 11

**Additional context**
n/a

**Comment by Gabbyxo97** [comment]
This also happens with chest items. Also, turns out the items don't have a name in the log file (there's never an item name after "Holding a(n)")

**Comment by rotobash** [comment]
Hi, thanks for reporting this.

The dreaded `???!` item 😞 I think something has gone wonky with items in Colosseum, I was going to ask you for the log file but you're right the names are busted so that won't help. I chalked that up to maybe the name offsets being wrong for Colosseum, since those aren't modified it wouldn't be a huge deal, but it looks like they are just not working period. Quick question, is this the EU or US version?

**Comment by Gabbyxo97** [comment]
EU version. I randomized the US version to check it out and seems to be an EU version issue because my US version I haven't seen the ??? item yet

**Comment by danielkillsya2** [comment]
Happening in the US version, worst part of it is it seems very common. Playing XD and 50% of the chests contain the ??? item and give you nothing. Chests, held items, etc all happen.

**Comment by rotobash** [comment]
Hi all, sorry for long ass delay in responding. I've been putting off working on this project for a long time now, longer than I should have. In any case, I want to sort these issues out and release something good for you all. 

I'm hoping this is fixed from #80, I have a few other fixes I want to tackle before releasing a new version and I'm hoping to release something by this weekend. Once that is released please open an issue if you encounter these junk items again. Thank you!
