### ISSUE TITLE
[BUG] Unable to randomize ISO, PC RAM usage caps at 99% and slows

### ISSUE THREAD

**Issue by SithLordLuxray** [rotobash/pokemon-ngc-rando#65]
**Describe the bug**
Unable to randomize GoD, gets stuck on Pokemon traits and RAM usage slowly increases over the course of 30 minutes until it caps out at 99%, slowing my PC drastically and crashing the randomizer. (I have 32GB of RAM if that makes a difference)

**Settings You Used**
( settings file attached)
Tried removing "force fully evolved" and "similar strength" based off a prior issue posted before to no avail.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.3.2 (latest)
 
[test.txt](https://github.com/rotobash/pokemon-ngc-rando/files/9440385/test.txt)

**Comment by rotobash** [comment]
Hi, thanks for reporting this!

I have a feeling this has to do with the GoD rom, I haven't tested randomizing it too much myself. I've had others tell me they were able to, so maybe certain settings don't play well. Let me take a look into this with the settings you provided and I'll get back to you with my findings.

Quick note: if the randomization takes longer than ~10-15 min something is up, you can kill it and report a bug here.

Cheers

**Comment by SithLordLuxray** [comment]
Verified my iso was good and tried again with no luck; however it seems to have been a weird issue with my iso file and the backup I had. Friend gave me theirs and it works fine now. Sorry to take up your time!
