### ISSUE TITLE
[BUG] Cannot Use Certain Settings Inside the Program

### ISSUE THREAD

**Issue by JByrd94** [rotobash/pokemon-ngc-rando#68]
So put simply, when I boot up the program, the options to "set minimum catch rate", "force fully evolved by %" and "Boost trainer Pokemon level by %" are not showing for me. The check boxes are present, but not the adjustable options. Not sure if this is a glitch in the program or just something that I'm doing wrong.
![Randomizer Error Screenshot](https://user-images.githubusercontent.com/50967960/198755672-99c52303-11d0-42d0-9453-d05e61b2ab8e.png)

**Describe the bug**

**Settings You Used**
Please upload the `*.settings` file you used to randomize with.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.3.2

**Additional context**

**Comment by rotobash** [comment]
Hi there, 

Thanks for the report. That's pretty strange, if you check the options do the number boxes appear? It's set to be disabled if the corresponding option isn't checked (and v.v.) but perhaps it's treating disabled as hidden.

If that doesn't work, then I'd try updating your .NET 5 runtime. Maybe it's a bug in that specific version? I tried downloading the latest prebuilt release and those boxes appear for me.

**Comment by JByrd94** [comment]
![Screenshot2](https://user-images.githubusercontent.com/50967960/200152008-73c0b25e-f4fe-40b9-81e2-b1d2d22fad1d.PNG)
So I downloaded specifically 5.0.16 of the .net program (since I did a little bit of searching and saw that specific version in one of the runtime files for the randomizer) and that didn't fix anything. And yes even if I check the options, the boxes do not appear next to the option

**Comment by JByrd94** [comment]
I get the feeling it's got to be something with my computer or something, because even with that newer version the options were still not showing for me

**Comment by rotobash** [comment]
Closing this. Sorry we couldn't figure it out. Please re-open if you want to troubleshoot more.
