### ISSUE TITLE
[Colosseum]  Support for colosseum

### ISSUE THREAD

**Issue by Laxes** [rotobash/pokemon-ngc-rando#7]
Do you have any plans on finishing the randomizer to support pokemon colosseum?

**Comment by rotobash** [comment]
Hey thanks for reminding me! I've finished up Colosseum support #8 

There's a new release version so give it a spin when you have a chance. Let me know if you encounter any strangeness, I only played up to Agate village on the US version and Miror B's hideout in Phenac City in the EU version to test everything.
