### ISSUE TITLE
[BUG] Wont download .NET

### ISSUE THREAD

**Issue by arbiter1019** [rotobash/pokemon-ngc-rando#72]
**Describe the bug**
When opening the randomizer file it says "To run this application you must install .NET. Would you like to download it now?". After clicking yes, it does nothing

**Settings You Used**
NA

**Expected behavior**
I expected .NET to download

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by rotobash** [comment]
This is most likely a Windows bug. I haven't added anything to check for the .NET version. Make sure the proper runtime is installed before opening (there's a link on the README). I plan to update the .NET version to a supported one soon.
