### ISSUE TITLE
[BUG] additional app Needed?

### ISSUE THREAD

**Issue by Botendo** [rotobash/pokemon-ngc-rando#75]
**Describe the bug**
I try to open the randomizer and my computer says i need another app to run it. it worked fine on my old computer with windows 10.
I just got a new computer with windows 11 installed, and thats really the only difference i can think of

**Settings You Used**
N/A

**Expected behavior**
on previous computer with Windows 10

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version (Current(?))

**Additional context**

**Comment by rotobash** [comment]
Updating Windows may have uninstalled the .NET runtime version needed to work. .NET 5 is unsupported so likely it's silently trying to prevent you from running it. I plan to update the runtime version soon to something more modern.
