### ISSUE TITLE
[BUG] Plenty of bugs abound!

### ISSUE THREAD

**Issue by ScrapDragon2** [rotobash/pokemon-ngc-rando#78]
**Describe the bug**
There's actually a series of bugs that I've found while playtesting this randomizer.
1. There is an abundance of ???! items -- which effectively are "nothing" items. ???! items that get attached to a caught Pokemon is stuck on that Pokemon and cannot be removed. This is caused by bad indexing in the item shuffler.
2. Opposing Pokemon moves aren't adjusted correctly. For instance, when you shuffle opposing trainers' Pokemon, but not the moves, you can run into a Quilava with Icy Wind (which is impossible.)
3. You can encounter Lv0 Pokemon in the PokeSpots. Also impossible.
4. TMs use compatibility as if they are their base move. IE: In my seed, TM27 - Return was shuffled to Shadow Ball. This made it so that EVERYTHING could learn it, even though it shouldn't (like Pikachu, Quilava, and Feraligatr.) This means some TMs that are useless can go to everything, but useful TMs can be learned by nearly nothing.
5. The randomizer seems to heavily favor repeat Pokemon, and obsoletion Pokemon. I've had two Shadow Cyndaquils pop up (one from the Shadow Lab, and one from Hordel's Togepi), and two members of Shadow Totodile's family (a Shadow Totodile and not long later a Shadow Feraligatr.)

**Settings You Used**
I don't have the settings file.

**Expected behavior**
1. Not running into effectively "nothing" items. Over half of the items in the game were ???! items.
2. Moves to be properly adjusted to the proper level-up movesets.
3. Levels are meant to be assigned a range in the PokeSpots.
4. TM compatibility should be based on the move it shuffles to, not what the base TM was.
5. Add more logic to prevent duplicate Pokemon. There's 386 available. 387 if you somehow add in Bonsly.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 22H2

**Additional context**
I'm not a programmer, but I'd be more than willing to help playtest this. Right now, the randomizer feels EXCEPTIONALLY barebones, like an alpha build. It has potential, but isn't being updated anymore.

I'll add more to this as I come across issues.

**Comment by rotobash** [comment]
Hi,

Sorry for the long delay in response. I have released a new version that should address your points here. Understandable if you've lost interest in the meantime but I wanted to comment to let you know wat's changed in any case.

1. This should be fixed, the indices of items in game jump around and there were a few instances of the code using the list index and not the item index.
3. Before randomizing, the program will now build a legal move list from TMs, Tutor Moves and Level Up Moves. If you don't set any move randomization options it will still update the move set to be legal moves only. (This is from a quirk in the game where trainer pokemon moves can be set to anything whether or not they're legal, it's why Miror B's Ludicolo uses Hydro Pump in vanilla)
4. I still have to look into this, I'm not really sure why this happens. I have seen it happen without touching pokespot pokemon so there must be something else mucking it up. I will spin this out into a new issue to keep investigating it.
5. This should be fixed as well. The randomizer will go through every pokemon and update compatibility whenever TM or tutor moves are changed.
6. I've tried hard to add safeguards to prevent duplication. Preventing families is a little more complicated and not implemented. There are a few possibilities on why it picks duplicates often. Preventing duplicates has a possibility of "running out" of pokemon depending on the settings, so it will pick duplicates if it can't fulfill the criteria for it (i.e. only strong pokemon with same type). Also, RNG is not really random and have a tendency to "cycle" through the same values depending on the seed you pick, you can try the cryptographic setting for "true" randomness.

Thanks for reporting this
