### ISSUE TITLE
[BUG] Despite having .net runtime still errors out asking for it

### ISSUE THREAD

**Issue by YukiRainee** [rotobash/pokemon-ngc-rando#82]
![image](https://github.com/rotobash/pokemon-ngc-rando/assets/6981053/c8d7d8c3-765d-460c-84ed-018605667875)
![image](https://github.com/rotobash/pokemon-ngc-rando/assets/6981053/cd17842f-2d17-4e02-96cd-86df0910997f)

**Desktop (please complete the following information):**
OS: Windows 10

**Additional context**

**Comment by YukiRainee** [comment]
solved the issue partially on my own and just built it meself from the master code here

**Comment by rotobash** [comment]
Hey, 

Yea .NET 5 is out of date now. The master branch contains an upgrade to .NET 8 but hasn't been consolidated into a release yet. I have a few issues I wanted to fix before making a release. Glad you were able to build a version though. I will be making an official one soon!

**Comment by abarlas** [comment]
FYI: For anyone else that wants to know how to do this. 

1. Go to the main code page, top right there's 'code' in green click it and download zip.
2. Unzip the file and inside you will see a shell script, it's called build.sh, on Windows you can double click this and it will run.
3. You'll get two new files, one of which is called ngc-randomizer.
4. Inside you'll find Randomizer.exe, assuming you have .Net 8 installed (link in the Readme) then you're good to go.

**Comment by Ajdorito** [comment]
Im not super good with computers and I for the life of me can't figure out how to get this to run. I have .NET 8 installed and I still get the error message and I even tried following the instructions in the above comment but I can't run the build.sh file :(

**Comment by Z-Target** [comment]
An easier way to get this to work, as I've found just recently, is to open the file named _randomizer.runtimeconfig.json_ in a text editor program like Notepad, and change all the 5's to 8's. Works perfectly.
